"use client";
import {useEffect,useMemo,useRef,useState} from "react";

type Voice=SpeechSynthesisVoice;
type HeadTTSLike={connect:()=>Promise<void>;setup:(x:any)=>Promise<any>;synthesize:(x:any)=>Promise<any[]>};
const PRESETS={Narrator:{voice:"af_bella",speed:0.92},Deep:{voice:"am_fenrir",speed:0.88},Energetic:{voice:"am_adam",speed:1.08},Calm:{voice:"af_sky",speed:0.82}} as const;
export default function Home(){
 const [text,setText]=useState("Welcome to Rapsometeddy Voice Studio. Turn your ideas into sound.");
 const [voices,setVoices]=useState<Voice[]>([]); const [voice,setVoice]=useState(""); const [rate,setRate]=useState(1); const [pitch,setPitch]=useState(1); const [speaking,setSpeaking]=useState(false);
 const [generating,setGenerating]=useState(false); const [status,setStatus]=useState("Ready"); const [audioUrl,setAudioUrl]=useState(""); const [telegramChat,setTelegramChat]=useState(""); const [neuralVoice,setNeuralVoice]=useState("af_bella");
 const headtts=useRef<HeadTTSLike|null>(null); const lastAudio=useRef<Blob|null>(null);
 useEffect(()=>{const load=()=>{const v=window.speechSynthesis.getVoices();setVoices(v);if(v.length&&!voice)setVoice(v[0].name)};load();window.speechSynthesis.addEventListener("voiceschanged",load);return()=>window.speechSynthesis.removeEventListener("voiceschanged",load)},[voice]);
 const selected=useMemo(()=>voices.find(v=>v.name===voice),[voices,voice]);
 const speak=()=>{if(!text.trim())return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);if(selected)u.voice=selected;u.rate=rate;u.pitch=pitch;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(u)};
 const stop=()=>{window.speechSynthesis.cancel();setSpeaking(false)}; const pause=()=>{if(window.speechSynthesis.speaking)window.speechSynthesis.pause()}; const resume=()=>{if(window.speechSynthesis.paused)window.speechSynthesis.resume()};
 const applyPreset=(name:keyof typeof PRESETS)=>{const p=PRESETS[name];setNeuralVoice(p.voice);setRate(p.speed);setStatus(name+" preset selected");};
 const generate=async()=>{if(!text.trim()||generating)return;if(text.length>500){setStatus("Keep generated text under 500 characters.");return}setGenerating(true);setStatus("Loading neural voice engine…");try{if(!headtts.current){const mod=await import("@met4citizen/headtts");const T=(mod as any).HeadTTS;if(!T)throw new Error("HeadTTS module did not load.");const t=new T({endpoints:["webgpu","wasm"],languages:["en-us"],voices:["af_bella","am_fenrir","am_adam","af_sky"],workerModule:"https://cdn.jsdelivr.net/npm/@met4citizen/headtts@1.3.0/modules/worker-tts.mjs",dictionaryURL:"https://cdn.jsdelivr.net/npm/@met4citizen/headtts@1.3/dictionaries/",defaultVoice:"af_bella",defaultLanguage:"en-us",defaultAudioEncoding:"wav"});await t.connect(null,(p:any)=>{if(p?.loaded!=null)setStatus("Loading neural model… "+Math.round(p.loaded*100)+"%")});headtts.current=t}const t=headtts.current!;await t.setup({voice:neuralVoice,language:"en-us",speed:rate,audioEncoding:"wav"});setStatus("Generating WAV… first run can take a while on a phone.");const messages=await Promise.race([t.synthesize({input:text}),new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error("TTS generation timed out after 120 seconds.")),120000))]);const audioMessages=(messages||[]).filter((m:any)=>m.type==="audio");const buffers=audioMessages.map((m:any)=>m.data??m.binary??m.buffer??m.audio).filter(Boolean);if(!buffers.length)throw new Error("No audio data returned by the neural engine.");const blob=new Blob(buffers,{type:"audio/wav"});if(audioUrl)URL.revokeObjectURL(audioUrl);const url=URL.createObjectURL(blob);setAudioUrl(url);lastAudio.current=blob;setStatus("WAV ready ✓");new Audio(url).play().catch(()=>{});}catch(e){console.error(e);setStatus(e instanceof Error?e.message:"Neural generation failed — browser preview still works.");}finally{setGenerating(false)}};
 const download=()=>{if(!audioUrl)return;const a=document.createElement("a");a.href=audioUrl;a.download="rapsometeddy-voice.wav";a.click()};
 const downloadMp3=async()=>{if(!audioUrl)return;setStatus("Encoding MP3…");try{const {default:lamejs}=await import("lamejs");const ab=await fetch(audioUrl).then(r=>r.arrayBuffer());const ctx=new AudioContext();const buf=await ctx.decodeAudioData(ab);const samples=buf.getChannelData(0);const pcm=new Int16Array(samples.length);for(let i=0;i<samples.length;i++)pcm[i]=Math.max(-32768,Math.min(32767,Math.round(samples[i]*32767)));const enc=new lamejs.Mp3Encoder(1,buf.sampleRate,128);const chunks:any[]=[];const block=1152;for(let i=0;i<pcm.length;i+=block){const chunk=enc.encodeBuffer(pcm.subarray(i,i+block));if(chunk.length)chunks.push(new Int8Array(chunk))}const end=enc.flush();if(end.length)chunks.push(new Int8Array(end));const mp3=URL.createObjectURL(new Blob(chunks,{type:"audio/mpeg"}));const a=document.createElement("a");a.href=mp3;a.download="rapsometeddy-voice.mp3";a.click();setTimeout(()=>URL.revokeObjectURL(mp3),1000);setStatus("MP3 ready ✓");await ctx.close()}catch(e){console.error(e);setStatus("MP3 export failed; WAV is still available.")}};
 const telegram=async()=>{if(!lastAudio.current){setStatus("Generate a WAV first.");return}if(!telegramChat.trim()){window.open("https://t.me/RapsometeddyHQBot","_blank");setStatus("Open the Rapsometeddy Telegram bot.");return}setStatus("Sending to Telegram…");try{const fd=new FormData();fd.append("audio",lastAudio.current,"rapsometeddy-voice.wav");fd.append("chatId",telegramChat.trim());fd.append("caption","Rapsometeddy Voice Studio");const r=await fetch("/api/telegram/send",{method:"POST",body:fd});if(!r.ok)throw new Error("Telegram send failed");setStatus("Sent to Telegram ✓")}catch(e){setStatus("Telegram needs Vercel bot environment variables.");}};
 return <main><header><div className="brand"><div className="logo">R<span>♛</span></div><div><b>RAPSOMETTEDY</b><small>VOICE STUDIO 1.1</small></div></div><span className="badge">NEURAL TTS • WAV • TELEGRAM</span></header><section className="hero"><p className="eyebrow">CREATE • GENERATE • EXPORT</p><h1>Your voice lab,<br/><em>in your pocket.</em></h1><p className="sub">Neural voice generation, presets and downloadable audio — built mobile-first for the Rapsometeddy ecosystem.</p></section><section className="studio"><div className="card"><div className="cardtop"><span>VOICE SCRIPT</span><span>{text.length}/500</span></div><textarea maxLength={500} value={text} onChange={e=>setText(e.target.value)} placeholder="Write something to generate..."/><div className="actions"><button className="primary" onClick={generate} disabled={generating}>{generating?"◌ GENERATING…":"🎧 GENERATE AUDIO"}</button><button onClick={speak}>▶ PREVIEW</button><button onClick={pause}>Ⅱ PAUSE</button><button onClick={stop}>■ STOP</button></div>{audioUrl&&<div className="export"><audio controls src={audioUrl}/><div className="actions"><button onClick={download}>💾 DOWNLOAD WAV</button><button onClick={downloadMp3}>🎵 DOWNLOAD MP3</button><button onClick={telegram}>🤖 SEND TELEGRAM</button></div></div>}</div><div className="card controls"><label>VOICE<select value={voice} onChange={e=>setVoice(e.target.value)}>{voices.length?voices.map(v=><option key={v.name} value={v.name}>{v.name}{v.lang?" • "+v.lang:""}</option>):<option>Browser voices loading…</option>}</select></label><label>PRESETS<div className="presetgrid">{Object.keys(PRESETS).map(x=><button key={x} onClick={()=>applyPreset(x as keyof typeof PRESETS)}>{x}</button>)}</div></label><label>RATE <output>{rate.toFixed(1)}×</output><input type="range" min=".5" max="2" step=".1" value={rate} onChange={e=>setRate(+e.target.value)}/></label><label>PITCH <output>{pitch.toFixed(1)}</output><input type="range" min=".5" max="2" step=".1" value={pitch} onChange={e=>setPitch(+e.target.value)}/></label><label>TELEGRAM CHAT ID<input className="textinput" value={telegramChat} onChange={e=>setTelegramChat(e.target.value)} placeholder="Optional"/></label><p className="status">{status}</p></div></section><section className="info"><div><b>01</b><h3>Neural generation</h3><p>Kokoro/HeadTTS runs in-browser using WebGPU or WASM and can produce WAV audio without a paid TTS API.</p></div><div><b>02</b><h3>Voice presets</h3><p>Quick starting points for narrator, deep, energetic and calm delivery.</p></div><div><b>03</b><h3>Telegram ready</h3><p>Generate here, download the WAV, or send it through your Rapsometeddy bot when its server environment is configured.</p></div></section><footer>RAPSOMETTEDY • BUILD • LEARN • CREATE • INVEST</footer></main>}