"use client";
import {useEffect,useMemo,useState} from "react";

type Voice=SpeechSynthesisVoice;
export default function Home(){
 const [text,setText]=useState("Welcome to Rapsometeddy Voice Studio. Turn your ideas into sound.");
 const [voices,setVoices]=useState<Voice[]>([]); const [voice,setVoice]=useState(""); const [rate,setRate]=useState(1); const [pitch,setPitch]=useState(1); const [speaking,setSpeaking]=useState(false);
 useEffect(()=>{const load=()=>{const v=window.speechSynthesis.getVoices();setVoices(v);if(v.length&&!voice)setVoice(v[0].name)};load();window.speechSynthesis.addEventListener("voiceschanged",load);return()=>window.speechSynthesis.removeEventListener("voiceschanged",load)},[voice]);
 const selected=useMemo(()=>voices.find(v=>v.name===voice),[voices,voice]);
 const speak=()=>{if(!text.trim())return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);if(selected)u.voice=selected;u.rate=rate;u.pitch=pitch;u.onstart=()=>setSpeaking(true);u.onend=()=>setSpeaking(false);u.onerror=()=>setSpeaking(false);window.speechSynthesis.speak(u)};
 const stop=()=>{window.speechSynthesis.cancel();setSpeaking(false)};
 const pause=()=>{if(window.speechSynthesis.speaking)window.speechSynthesis.pause()}; const resume=()=>{if(window.speechSynthesis.paused)window.speechSynthesis.resume()};
 return <main><header><div className="brand"><div className="logo">R<span>♛</span></div><div><b>RAPSOMETTEDY</b><small>VOICE STUDIO</small></div></div><span className="badge">FREE • NO API KEY</span></header><section className="hero"><p className="eyebrow">CREATE • SPEAK • EXPLORE</p><h1>Your voice lab,<br/><em>in your pocket.</em></h1><p className="sub">A lightweight browser voice studio built for mobile. No account, subscription or API key needed.</p></section><section className="studio"><div className="card"><div className="cardtop"><span>VOICE SCRIPT</span><span>{text.length}/5000</span></div><textarea maxLength={5000} value={text} onChange={e=>setText(e.target.value)} placeholder="Write something to speak..."/><div className="actions"><button className="primary" onClick={speak}>{speaking?"RESTART":"▶ SPEAK"}</button><button onClick={pause}>Ⅱ PAUSE</button><button onClick={resume}>▶ RESUME</button><button onClick={stop}>■ STOP</button></div></div><div className="card controls"><label>VOICE<select value={voice} onChange={e=>setVoice(e.target.value)}>{voices.length?voices.map(v=><option key={v.name} value={v.name}>{v.name}{v.lang?" • "+v.lang:""}</option>):<option>Loading browser voices…</option>}</select></label><label>RATE <output>{rate.toFixed(1)}×</output><input type="range" min=".5" max="2" step=".1" value={rate} onChange={e=>setRate(+e.target.value)}/></label><label>PITCH <output>{pitch.toFixed(1)}</output><input type="range" min=".5" max="2" step=".1" value={pitch} onChange={e=>setPitch(+e.target.value)}/></label></div></section><section className="info"><div><b>01</b><h3>Browser powered</h3><p>Uses your device's built-in speech engine, so the first version stays free and fast.</p></div><div><b>02</b><h3>Mobile first</h3><p>Designed around a small screen and touch controls for your Galaxy or any modern phone.</p></div><div><b>03</b><h3>Next up</h3><p>Audio export, richer voices and Telegram integration can be added as the studio grows.</p></div></section><footer>RAPSOMETTEDY • BUILD • LEARN • CREATE • INVEST</footer></main>}